# Generated by Django 4.0.3 on 2022-11-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenpost'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=models.TextField(max_length=2000),
        ),
    ]
