# Generated by Django 4.0.3 on 2022-11-10 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_imagen_alter_post_cuerpo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
    ]
