# Generated by Django 4.0.3 on 2022-11-10 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_remove_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
