# Generated by Django 4.0.3 on 2022-11-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_comentario_activo_alter_comentario_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='post',
        ),
    ]
