# Generated by Django 4.0.3 on 2022-10-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='subtitulo_blog',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='titulo_blog',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
