# Generated by Django 4.0.3 on 2022-10-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_configuracion_subtitulo_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='desarrollado_por',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
