# Generated by Django 4.0.3 on 2022-11-10 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Contact',
        ),
    ]
