# Generated by Django 4.0.3 on 2022-10-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_configuracion_desarrollado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('sub_titulo', models.CharField(max_length=30)),
                ('cuerpo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=15)),
            ],
        ),
    ]
