# Generated by Django 4.0.3 on 2022-11-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_contact_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigContact',
        ),
    ]
