# Generated by Django 4.0.3 on 2022-10-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('sub_titulo', models.CharField(max_length=40)),
                ('cuerpo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=15)),
            ],
        ),
    ]
