# Generated by Django 4.0.3 on 2022-10-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_post_imagen_blog_post_sub_titulo_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='cuerpo_1',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='cuerpo',
            field=models.CharField(max_length=500),
        ),
    ]
