# Generated by Django 4.0.3 on 2022-11-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigAbout',
        ),
        migrations.DeleteModel(
            name='ConfigIndex',
        ),
    ]
