# Generated by Django 4.0.3 on 2022-10-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_post_cuerpo_1_alter_blog_post_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='link_informacion',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='cuerpo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='cuerpo_1',
            field=models.CharField(max_length=700),
        ),
    ]
