# Generated by Django 4.0.3 on 2022-10-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_post_link_informacion_alter_blog_post_cuerpo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='link_informacion',
            field=models.CharField(max_length=200),
        ),
    ]
