# Generated by Django 4.0.3 on 2022-10-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_post_link_informacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cuerpo',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='link_informacion',
        ),
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
