# Generated by Django 4.0.3 on 2022-10-31 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blog_cuerpo_remove_blog_post_link_informacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imagen',
        ),
    ]
