# Generated by Django 4.0.3 on 2022-10-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sub_titulo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=25),
        ),
    ]
