# Generated by Django 4.0.3 on 2022-11-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_sub_titulo_alter_blog_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_blog', models.CharField(max_length=14)),
                ('titulo_blog', models.CharField(max_length=20)),
                ('subtitulo_blog', models.CharField(max_length=30)),
                ('desarrollado_por', models.CharField(max_length=30)),
            ],
        ),
    ]
