# Generated by Django 4.0.3 on 2022-11-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_configuracion1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuracion1',
            new_name='ConfiguracionBlog',
        ),
    ]
