# Generated by Django 4.0.3 on 2022-11-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_configuracionblog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('sub_titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RenameField(
            model_name='configuracion',
            old_name='subtitulo_blog',
            new_name='sub_titulo',
        ),
        migrations.RenameField(
            model_name='configuracion',
            old_name='titulo_blog',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
