# Generated by Django 4.0.3 on 2022-11-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_delete_blog_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
