# Generated by Django 4.0.3 on 2022-11-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_delete_blog_post_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pagina', models.CharField(max_length=20)),
                ('nombre_blog', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=20)),
                ('sub_titulo', models.CharField(max_length=30)),
                ('link_github', models.CharField(max_length=60)),
                ('desarrollado_por', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('sub_titulo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('sub_titulo', models.CharField(max_length=30)),
                ('sub_titulo_1', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Configuracion',
            new_name='ConfigAbout',
        ),
    ]
