# Generated by Django 4.0.3 on 2022-11-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_configbase_configcontact_configindex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configbase',
            name='sub_titulo',
        ),
        migrations.RemoveField(
            model_name='configbase',
            name='titulo',
        ),
    ]
