# Generated by Django 4.0.3 on 2022-11-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_configbase_link_github'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigBase',
        ),
    ]
