# Generated by Django 4.0.3 on 2022-11-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_delete_configbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configabout',
            name='sub_titulo',
            field=models.CharField(max_length=200),
        ),
    ]
