# Generated by Django 4.0.3 on 2022-11-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_configabout_sub_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcontact',
            name='sub_titulo',
            field=models.CharField(max_length=50),
        ),
    ]
