# Generated by Django 4.0.3 on 2022-11-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_perfil_apellido_perfil_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='User',
        ),
    ]
