# Generated by Django 4.0.3 on 2022-11-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
