# Generated by Django 4.0.3 on 2022-11-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
