# Generated by Django 4.0.3 on 2022-11-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0008_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='nombre_usuario',
            new_name='nombre_perfil',
        ),
    ]
