# Generated by Django 4.0.3 on 2022-11-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0009_rename_nombre_usuario_perfil_nombre_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
    ]
