# Generated by Django 4.0.3 on 2022-11-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0012_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
