# Generated by Django 4.0.3 on 2022-11-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0015_rename_usuario_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
