# Generated by Django 4.0.3 on 2022-11-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0017_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
